esphome:
  name: ambient

esp32:
  board: featheresp32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "DENBend"
  password: "d3mandbend"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ambient Fallback Hotspot"
    password: "VUfKFoWbZgOP"

captive_portal:
    
sensor:
  platform: dht
  model: DHT22
  pin: GPIO4
  temperature:
    name: "Temp"
  humidity:
    name: "Hum"
  update_interval: 5s

